baseURL = "http://example.com/"
languageCode = "en-us"
title = "Lionel Ngoubou"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Lionel Ngoubou"
    description = "Aspirant Data Scientist"
    githubUsername = "#"
    accent = "black"
    showBorder = true
    backgroundColor = "green"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Pr"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:ralphngoubou@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ngoubou/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/LioNgoubou/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/lionel-ngoubou/"
    name = "linkedin"
    weight = 4
