---
title: Analyse de la draft NBA
author: Lionel Ngoubou
date: '2020-02-26'
slug: analyse-de-la-draft-nba
categories: []
tags: []
---

La NBA a connu une évolution notable il y a de cela quelques années avec l’introduction des statistiques dites avancées. Cela a considérabkement modifié l’approche du jeu et a également eu une incidence sur l’évaluation des joueurs. L’accent a été particulièrement mis sur l’efficacité. Profusion du tir à 3 points avec le “Morey Ball”, démocratisation du “Small Ball” et bien d’autres.

Le but de cette analyse est donc de voir comment cette (r)évolution se traduit. Nous avons donc axé notre analyse sur deux axes : la draft et le temps de jeu. Notre hypothèse étant que si le jeu penche de plus en plus vers l’éxtérieur, cela devrait se traduire par les joueurs sélectionnés ainsi que le temps que ces derniers passent sur le parquet. Nous avons donc décidé d’analyser les drafts des dix dernières années (2009 à 2019 inclus) afin de voir si ces tendances se traduisaient dans ces données.

Dans un premier temps nous nous intéressons aux choix faits à la draft. Pour cela, nous avons classé les joueurs dans quatre catégories qui sont les suivantes : Big : pour les pivots et ailiers forts. Exemple : Al Horford ou LaMarcus Aldridge Forward : pour les ailiers et/ou ailiers forts. Exemple : Pascal Siakam, Kevin Durant, Brandon GOAT Ingram. Guard : pour les arrières et/ou meneurs. Exemple : Steph Curry, Trae Young, Lonzo Ball Swing : pour les arrières pouvant évoluer à l’aile. Exemple : RJ Barrett, DeMar Derozan, Andre Iguodala.

Une fois ces catégories établies, nous avons comptabilisé les différents choix et les avons répartis selon les catégories correspondantes. Nous avons ensuite visualisé cette répartition avec un diagramme à barres (barplot).

Par la suite, nous nous sommes intéressés au temps de jeu de ces joueurs draftés entre 2009 et 2019 afin de voir ceux qui passent le plus de temps sur le terrain. Ce qui pourrait se traduire par un rôle important.

Notre analyse montre que les Guards sont non seulement ceux qui ont le plus de “représentents” à la draft sur ces dix dernières années, mais qu’ils sont également ceux avec le temps de jeu le plus élevé. Ils sont suivis par les Forwards, les Bigs et enfin les Swings.

Cette analyse pourrait éventuellement en amener une autre qui établirait une comparaison entre la saison régulière et les playoffs.